### ISSUE TITLE
Logic for Incoming - No Match

### ISSUE THREAD

**Issue by mistermichaelll** [samwang1/hingeify#1]
Hi Sam, 

I was taking a look at your project and it's awesome, love the use of R & Shiny!

I was taking a look at some of the code (as I'm curious about untangling Hinge's messy data export and tidying it up) and I was wondering about the logic for counting up the _Incoming Likes with No Match_. 

```r 
# incoming matches--they liked you first, you liked them back
incoming_matches <- nrow(matches %>% filter(like == "NULL" & block == "NULL"))

# incoming likes, removed--they liked you, you didn't like them back
incoming_removed <- nrow(removed %>% filter(like == "NULL"))
```

My understanding of the logic for the incoming likes without matching is this:

```
IF 
     'block' IS NOT NULL 
AND 
     'like' IS NULL 
THEN 
     'Incoming Like - Didn't Like them Back'
```

However, looking at my own data, there are "incoming like - didn't like them back" with chats associated with them – which would imply that I _did_ like them back. My theory is that this is capturing people who I received a like from, chatted with, but eventually unmatched. 

```r
nrow(removed %>% filter(like == "NULL" & chats != "NULL"))
#> [1]    27
```

If this isn't intentional, I'm wondering if the logic should be adjusted like this:

```r
# incoming matches--they liked you first, you liked them back
# (eg., the "like" column is blank but the match column is not. 
# if we include the block column as part of the logic, we are 
# excluding matches we later unmatched.)
incoming_matches <- nrow(matches %>% filter(like == "NULL")) 

# incoming likes, removed--they liked you, you didn't like them back
incoming_removed <- nrow(removed %>% filter(like == "NULL" & match == "NULL")) 

# verify that there are no chats associated with incoming, not liked back
# nrow(removed %>% filter(like == "NULL" & match == "NULL" & chats != "NULL"))
#> [1]    0
```

When I implement the changed logic in Python - the numbers for matches, likes received, matches from likes, etc. all come out to be the same as your app displays. So this may be a redundant issue submission.

What are your thoughts? 😄

**Comment by samwang1** [comment]
Hi Michael,

Thanks for the feedback! It turns out that the GitHub version of my files are out of date. You are right that I should change the logic of incoming likes with no match. In my code, I have an added filter condition to have no chats, but they essentially mean the same thing:
`
incoming_removed <- nrow(removed %>% filter(like == "NULL" & match == "NULL" & chats == "NULL"))
`
The numbers look the same in your Python version because they are actually the same as what's on the website right now. I have pushed the correct version. My bad!
